Namespace(net='oneprompt', baseline='unet', seg_net='transunet', mod='one_adpt', exp_name='basic_exp', type='map', vis=None, reverse=False, pretrain=False, val_freq=100, gpu=True, gpu_device=0, sim_gpu=0, epoch_ini=1, image_size=1024, out_size=256, patch_size=4, dim=256, depth=1, heads=16, mlp_dim=1024, w=4, b=64, s=True, warm=1, lr=0.0001, uinch=1, imp_lr=0.0003, weights=0, base_weights=0, sim_weights=0, distributed='none', dataset='oneprompt', one_ckpt=None, thd=False, chunk=1, num_sample=4, roi_size=96, evl_chunk=None, data_path='/fred/oz345/khoa/one-prompt/data/ISIC', path_helper={'prefix': 'logs/basic_exp_2024_10_31_16_36_49', 'ckpt_path': 'logs/basic_exp_2024_10_31_16_36_49/Model', 'log_path': 'logs/basic_exp_2024_10_31_16_36_49/Log', 'sample_path': 'logs/basic_exp_2024_10_31_16_36_49/Samples'})
/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/utils/deprecate_utils.py:321: FutureWarning: monai.transforms.croppad.dictionary CropForegroundd.__init__:allow_smaller: Current default value of argument `allow_smaller=True` has been deprecated since version 1.2. It will be changed to `allow_smaller=False` in version 1.5.
  warn_deprecated(argname, msg, warning_category)
Loading dataset:   0%|          | 0/24 [00:00<?, ?it/s]/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py:635: UserWarning: axcodes ('RAS') length is smaller than number of input spatial dimensions D=2.
Orientation: spatial shape = (1022, 767), channels = 3,please make sure the input is in the channel-first format.
  warnings.warn(
/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py:635: UserWarning: axcodes ('RAS') length is smaller than number of input spatial dimensions D=2.
Orientation: spatial shape = (1022, 767), channels = 1,please make sure the input is in the channel-first format.
  warnings.warn(
Loading dataset:   4%|▍         | 1/24 [00:00<00:13,  1.73it/s]Loading dataset:  42%|████▏     | 10/24 [00:00<00:00, 19.02it/s]/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py:635: UserWarning: axcodes ('RAS') length is smaller than number of input spatial dimensions D=2.
Orientation: spatial shape = (1504, 1129), channels = 3,please make sure the input is in the channel-first format.
  warnings.warn(
/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py:635: UserWarning: axcodes ('RAS') length is smaller than number of input spatial dimensions D=2.
Orientation: spatial shape = (1504, 1129), channels = 1,please make sure the input is in the channel-first format.
  warnings.warn(
Loading dataset:  67%|██████▋   | 16/24 [00:00<00:00, 23.72it/s]/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py:635: UserWarning: axcodes ('RAS') length is smaller than number of input spatial dimensions D=2.
Orientation: spatial shape = (1503, 1129), channels = 3,please make sure the input is in the channel-first format.
  warnings.warn(
/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/spatial/array.py:635: UserWarning: axcodes ('RAS') length is smaller than number of input spatial dimensions D=2.
Orientation: spatial shape = (1503, 1129), channels = 1,please make sure the input is in the channel-first format.
  warnings.warn(
Loading dataset:  88%|████████▊ | 21/24 [00:01<00:00, 24.58it/s]Loading dataset: 100%|██████████| 24/24 [00:01<00:00, 22.71it/s]
Loading dataset:   0%|          | 0/2 [00:00<?, ?it/s]Loading dataset:  50%|█████     | 1/2 [00:00<00:00,  7.23it/s]Loading dataset: 100%|██████████| 2/2 [00:00<00:00,  8.57it/s]Loading dataset: 100%|██████████| 2/2 [00:00<00:00,  8.34it/s]
Epoch 0:   0%|          | 0/15 [00:00<?, ?img/s]Exception in thread Thread-18 (enqueue_values):
Traceback (most recent call last):
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
                                                                               ^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/io/array.py", line 294, in __call__
    img = EnsureChannelFirst()(img)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/utility/array.py", line 200, in __call__
    raise ValueError(msg)
ValueError: Metadata not available and channel_dim=None, EnsureChannelFirst is not in use.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/compose.py", line 335, in __call__
    result = execute_compose(
             ^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/compose.py", line 111, in execute_compose
    data = apply_transform(
           ^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x14efe00013d0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/thread_buffer.py", line 49, in enqueue_values
    for src_val in self.src:
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/dataset.py", line 112, in __getitem__
    return self._transform(index)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/dataset.py", line 910, in _transform
    return super()._transform(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/data/dataset.py", line 98, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dpham/.conda/envs/oneprompt/lib/python3.11/site-packages/monai/transforms/transform.py", line 171, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x14efdfff7750>
Epoch 0:   0%|          | 0/15 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "/fred/oz345/khoa/one-prompt/train.py", line 82, in <module>
    loss = function.train_one(args, net, optimizer, nice_train_loader, epoch, writer, vis = args.vis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz345/khoa/one-prompt/function.py", line 176, in train_one
    return loss
           ^^^^
UnboundLocalError: cannot access local variable 'loss' where it is not associated with a value
